CausalInferenceLab/Lang2SQL

- interface/streamlit_app.py
- llm_utils/graph.py
- llm_utils/llm_factory.py
[이슈](https://github.com/CausalInferenceLab/Lang2SQL/issues/6#issuecomment-2709907899)에서 제안 주신 langchain에 built-in 되어 있는 `SQL_PROMPTS`를 사용하여 각자 다른 DB 환경에 맞게 SQL를 생성하도록 하였습니다.
Update 항목
- `llm_utils/graph.py` - `query_maker_node`와 같은 역할을 하는 `query_maker_node_with_db_guide`를 만들었습니다. 
- `llm_utils/graph.py` - SQL result를 `SQLResult`를 pydantic으로 정의하여 sql와 sql의 설명을 받도록 하여 sql에 불필요한 정보가 담기지 않고 sql의 설명을 이용하여 reasoning을 받아 사용자에게 설명하도록 하였습니다. 
- `interface/streamlit_app.py` - graph의 response가 변경되어 streamlit의 출력 부분을 업데이트 하였습니다.
- `interface/streamlit_app.py` - streamlit 상에서 `user_database_env`를 받는 방법을 `selectbox`로 변경하였습니다.
> 6 dbms별 sql 차이를 반영한 few shot prompt 최적화 제안

- .github/workflows/pr-notification.yml
- #27 
- PR 등록 시, Github Actions로 Telegram bot 호출을 수행합니다. 
- PR 병합 시에도 알람이 옵니다.
- 실제 해당 Repo에서도 동작이 되는 지 확인이 필요하며, Settings에 TOKEN 설정이 필요합니다 (WIKI 공유)
- 다음과 같이 PR 관련 알람이 오게 됩니다. 
> chore: pr notification telegram bot

- data_utils/datahub_source.py
- llm_utils/tools.py
- table_metadata2.json
- #5
- `datahub_source.py`에 DataHub lineage 정보를 추출하는 함수들을 추가했습니다.
- `get_table_lineage` : URN의 DOWNSTREAM/UPSTREAM lineage를 가져오는 함수
- `get_column_lineage` : URN의 UPSTREAM table의 column별 lineage를 가져오는 함수
- `min_degree_lineage` : 수많은 lineage 중 최소 degree만 가져오는 함수
- `build_table_metadata` : table name, desc, columns, lineage를 활용해 table metadata를 만드는 함수
- `tools.py`에 전체 테이블 메타데이터를 생성하는 `get_metadata_from_db()` 함수 추가했습니다.
- 테이블 이름, 설명, 컬럼 정보, 테이블/컬럼 단위 lineage 정보까지 포함해 반환하도록 구현했습니다.
- URN 파싱 및 lineage 추출 과정에서 추가적인 예외 처리나 개선할 부분이 있다면 리뷰 부탁드립니다.
- 메타데이터 구조나 반환 형태가 이후 사용 및 확장에 적절한지 확인해주시면 좋겠습니다.
get_metadata_from_db()의 반환 구조는 아래와 같습니다:
```python
[
{
"table_name": str,
"description": str,
"columns": [
{
"column_name": str,
"column_description": str
},
...
],
"lineage": {
"downstream": [{"table": …
```
> 5 데이터 카탈로그 description 개선방향

- llm_utils/tools.py
- TBD
- Datahub에서 설명을 받아올 때 너무 오랜 시간이 걸려 병렬처리를 
- 다른 곳에서 함수를 사용할 때 문제가 생기는지 확인이 필요합니다.
- Datahub 서버에 부하문제는 없을까요??
> feat: 테이블 및 컬럼 정보를 병렬로 수집하도록 개선하여 성능 향상

- requirements.txt
- #67 
- 바로 실행할 수 있도록 파이썬 라이브러리 최신화
- None
- None
> fix: update requirements.txt

- cli/__init__.py
- #69 
- URL 설정 및 Streamlit 실행을 명확히 분리
- 에러 핸들링 추가
- 타입 힌트 추가
- docstring 추가
- click 기반 확장성 유지
- 코드 스타일 통일
- None
> refact: lang2sql CLI 관련 코드 리펙토링

- interface/streamlit_app.py
- #71 
- 최상위 멀티 페이지 정의하도록 수정
- 정의된 딕셔너리 검증함수 추가
- None
> refact: streamlit 멀티 페이징 모듈 리펙토링 및 검증함수 추가

- interface/lang2sql.py
- llm_utils/chains.py
- llm_utils/graph.py
- llm_utils/retrieval.py
- requirements.txt
- setup.py
- #46 
- retrieve 할때 reranking을 쓸수 있도록 streamlit에 selectbox를 추가했습니다.
- 찾을 테이블 갯수도 streamlit에서 조정하도록 추가하였습니다.
- reranking시 `Dongjin-kr/ko-reranker` 모델을 통해 reranking 합니다.
- 한국어로 description이 적혀있다는 가정 (추후 Optional하게 변경해도 괜찮겠네요)
- 테이블을 찾는 부분을 `retrieval.py` 로 분리했습니다.
- **graph 순서를 아래와 같이 변경했습니다.**
- 1. 기존: QUERY_REFINER -> 현재: GET_TABLE_INFO
- 2. 기존: GET_TABLE_INFO -> 현재: QUERY_REFINER
- 3. QUERY_MAKER
- 이유는 회사에 적용했을때 유저질문을 재정의한 이후에 테이블을 찾으니 유저 입력과 관계없는 테이블이 너무 많이 찾아지는것을 경험하였습니다.
- 입력: `특정 서비스 분석`
- 재정의: `유저 접속과 매출을 고려하여 ~~~`
- 결과: 특정 서비스 관련 테이블이 나오는게 아니라 유저 접속이나 매출테이블들이 먼저 검색됨
- 순서 변경에 대해 피드백 부탁드립니다!
- 알약 (💊): 리뷰어가 리뷰이의 코드에서 개선된 방법을 제안하지만 그것의 반영이 필수까지는 아닐 …
> Feature/46 retrieve성능 향상

- interface/lang2sql.py
- llm_utils/connect_db.py
- #88 
- Database 연결 리펙토링 및 로깅 추가, DB 연결 두번 시도하는 현상 수정
- llm_utils/connect_db.py 코드 리펙토링
- 클래스 객체로 선언시 자동 연결 확인
- 로깅 추가
- lang2sql.py 기존 코드에서 두번씩 연결 확인하는 부분 수정
```bash
2025-05-01 11:13:11 [INFO] Successfully connected to ClickHouse.
2025-05-01 11:13:11 [INFO] Successfully connected to ClickHouse.
```
- 없음
> fix: logging and connect db refactoring

- .gitignore
- requirements.txt
- #85 
- 호환성을 위한 Numpy 버전관리 및 .gitignore 수정
- 없음
- 없음
> fix: update requirements.txt and .gitignore

- interface/lang2sql.py
- llm_utils/llm_response_parser.py
- #87 
- SQL Context 에러 수정 및 Streamlit UI 파싱 수정, 웹페이지 클리닝
- 없음
> fix: SQL Context 에러 수정 및 Streamlit UI 파싱 수정, 웹페이지 클리닝

- requirements.txt
- setup.py
- test/test_llm_utils/test_llm_response_parser.py
- #92 
- 신규 추가된 LLMResponseParse 모듈의 테스트코드 추가
- 없음
> 신규 추가된 LLMResponseParse 모듈의 테스트코드 추가

- setup.py
- #110 
작업 내용
현재는 파이썬 라이브러리를 requirements.txt, setup.py 두 곳에서 관리함.
requirements.txt만 관리하고, setup.py는 requirements.txt를 읽어서 사용하도록 수정
장점
의존성 정의의 중복 방지
setup.py와 requirements.txt에 각각 같은 패키지를 따로 관리하면, 버전 충돌, 누락 또는 중복, 설치 실패 등의 문제가 발생할 수 있음.
하나의 소스 오브 트루스(Source of Truth) 유지
패키지를 설치할 때는 requirements.txt를, 배포할 때는 setup.py를 참조하게 되면 관리 포인트가 2배가 됨.
한 곳만 수정하고 나머지는 깜빡하면 버그로 이어질 수 있음.
CI/CD 자동화에 유리
자동 테스트, 릴리스, Docker 이미지 빌드 등에서 일관된 의존성 관리가 필요함
pip install .과 pip install -r requirements.txt가 동일한 환경을 보장해야 예측 가능한 배포가 가능해짐.
- None
- `pip install .`
> requirements.txt를 setup.py에서 읽어서 사용

- pyproject.toml
- #99 
- pyproject.toml에 포함된 Poetry 설정으로 인해 pip install . 명령 실행 시 충돌이 발생.
- 이를 해결하기 위해 Poetry 관련 설정을 주석 처리하고, setuptools 기반의 빌드 시스템으로 정리했음.
- 이제 setup.py 기반 설치가 문제없이 동작하며, 빌드 시스템이 일관되게 유지됨
- 기존 코드는 주석으로 남겨둠.
- 없음.
- `pip install .`
> pip install 충돌 해결을 위한 Poetry 설정 제거

- llm_utils/tools.py
- Python 3.11 버전에서  병렬 처리를 위한 함수에서 Syntax Error 가 발생하여 수정하였습니다. 
- 현재 코드는 Python 3.12 버전 이상에서만 유효한 문법입니다.
- TBD
- TBD
> refactor: parallel_process 함수의 타입 매개변수 제거

- Dockerfile
- docker-compose.yml
- #47 
- pip install 이외에 docker-compose를 통해서 streamlit을 사용할 수 있게 Dockerfile과 docker-compose 파일을 설정했습니다.
- Streamlit뿐만 아니라 이전 회의에 나온 내부 DB로 Postgres를 추가적으로 이미지 설정해서 사용할 수 있게 연결했습니다.
- Postgres를 기반으로 추후 벡터 DB를 교체할 수 있을 것으로 생각됩니다
- Docker 및 Docker Compose가 설치된 환경에서 테스트를 해보실 수 있습니다 (추후 가이드 문서 작성)
- `docker-compsose up`으로 API를 올려보실 수 있습니다.
- 참고) docekr-compose down으로 이미지를 내릴 수 있습니다
> chore: Docker Image 설정 및 docker-compose 설정

- llm_utils/connect_db.py
- #101 
- run_sql() 호출 시점에만 ClickHouse에 연결하도록 로직을 변경하여 지연 연결(lazy connection) 방식을 적용했습니다.
- 누락된 환경 변수를 사전에 감지하기 위해 _get_env_or_raise() 함수를 도입하고, 명확한 예외와 에러 로그를 추가했습니다.
- 이로써 실행 안정성과 디버깅 편의성이 향상되었습니다.
- 없음
- `lang2sql --datahub_server http://34.16.140.205:8080 run-streamlit`
> ClickHouse 연결 지연(Lazy Connect) 방식 적용 및 환경 변수 검증 로직 추가

- llm_utils/tools.py
- #118 
- get_column_info 함수의 성능 최적화를 통해 테이블당 30-40초 걸리던 처리 시간을 대폭 단축 
- 기존 table_info 경로의 vector db 제거 후 재생성이 빠르게 되는지 테스트 부탁드립니다!
- TBD
> refactor: _get_column_info 함수 최적화

- data_utils/datahub_source.py
- #127 
- DatahubMetadataFetcher 클래스에서 데이터셋의 이름에 dbt_unique_id를 포함하여 반환하도록 수정
- 데이터베이스 정보와 테이블 정보를 결합하여 반환 형식 개선
- 시각화가 잘 되는지 체크 부탁드립니다.
- TBD
> feat: 데이터셋 이름에 데이터베이스 정보를 추가

- cli/__init__.py
- data_utils/datahub_services/__init__.py
- data_utils/datahub_services/base_client.py
- data_utils/datahub_services/glossary_service.py
- data_utils/datahub_services/metadata_service.py
- data_utils/datahub_services/query_service.py
- data_utils/datahub_source.py
- data_utils/queries.py
- llm_utils/chains.py
- llm_utils/retrieval.py
- llm_utils/tools.py
- TBD
- DatahubMetadataFetcher 클래스에 특정 URN으로 메타데이터, 연관 쿼리, 용어집 정보를 조회하는 기능(get_urn_info, get_queries_by_urn, get_glossary_terms_by_urn) 추가  
- 조회한 연관쿼리, 용어집 정보를 get_table_info_node - search_tables 에서 쓰도록 구현
- get_table_info_node 에서 등록하는 searched_tables 에 같이 등록되어 스크린샷과 같이 활용되는데 이 부분에 관해서 의견주시면 감사하겠습니다!
- 테스트는 `http://34.125.33.25:9002/` 로 떠있는 Datahub를 쓰셔도 무방합니다!
- TBD
> Feature/132 metadata 통합 강화 enhancement glossary쿼리예시 메타데이터를 sql 생성 컨텍스트에 반영

- interface/graph_builder.py
- interface/lang2sql.py
- version.py
> 그래프 빌더 및 Lang2SQL UI 업데이트 #134

- .gitignore
- README.md
- docs/tutorials/getting-started-without-datahub.md
- pyproject.toml
- #145 
- 튜토리얼대로 실행시 발생했던 에러로그를 수정 및 문서로 정리
- README.md 의 "빠른 설치" 와 "소스에서 설치" 시 파이썬 버전을 통일했습니다.
- 튜토리얼대로 실행시 아래 에러가 psycopg[binary] 관련 에러가 발생해 pyproject.toml 파일을 수정했습니다.
```bash
ImportError: no pq wrapper available.
Attempts made:
- couldn't import psycopg 'c' implementation: No module named 'psycopg_c'
- couldn't import psycopg 'binary' implementation: No module named 'psycopg_binary'
- couldn't import psycopg 'python' implementation: libpq library not found
```
- 튜토리얼대로 실행시 .env 파일을 읽지않고 로컬의 환경변수를 읽어서, .env 내용이 환경변수에 없는 경우 실패해 dotenv 를 사용해 create_faiss.py가 실행하도록 수정했습니다.
```python
from dotenv import load_dotenv
load_dotenv()
```
- 튜토리얼대로 실행시, DB_TYPE이 없을 때 실행되지 않는 문제가 있어서 문서에 DB_TYPE을 기본값으로 추가했습니다.
```bash
ValueError: DB type must be provided or set in environment as DB_TYPE.
```
- 튜토리얼의 …
> fix: 튜토리얼로 실행시 실패하는 현상 수정

- Dockerfile
- cli/__init__.py
- docker-compose.yml
- #148 
- `docker compose up -d` 실행시 Dockerfile로 이미지가 생성되지 않는 현상
```bash
E: Unable to locate package software-properties-common
failed to solve: failed to compute cache key: 
failed to calculate checksum of ref ... "/requirements.txt": not found
COPY pyproject.toml ./
RUN pip install --upgrade pip setuptools wheel \
&& pip install .
```
- `docker compose up -d`시 문제없시 실행되는지 확인
- N/A
> fix: 도커파일 이미지 빌드 실패현상 수정

- .gitignore
- README.md
- cli/__init__.py
- dev/create_faiss.py
- dev/create_pgvector.py
- docker/docker-compose.yml
- docs/tutorials/getting-started-without-datahub.md
- llm_utils/README.md
- llm_utils/vectordb/faiss_db.py
- #159 
- 튜토리얼 관련 파일을 dev/ 하위로 이동
- `lang2sql --vectordb-type faiss --vectordb-location ./dev/table_info_db run-streamlit`
- TBD
> refactor: 튜토리얼 관련 파일의 구조 변경

- interface/app_pages/lang2sql.py
- interface/core/lang2sql_runner.py
- interface/core/result_renderer.py
- interface/core/session_utils.py
- #182 
- 기존 lang2sql.py에 집중되어 있던 실행/결과 표시/세션 초기화 로직을 모듈 단위로 분리했습니다.
- UI 중심 코드와 내부 실행 로직을 구분하여 유지보수성과 확장성을 개선했습니다.
- Streamlit 페이지는 UI 전용으로 단순화되었습니다.
- 모듈 분리 구조(lang2sql_runner.py, result_renderer.py, session_utils.py)가 적절한지 확인 부탁드립니다.
- Lang2SQL 실행 로직 분리 (lang2sql_runner.py)
- 결과 표시 모듈화 (result_renderer.py)
- 세션 상태 초기화 분리 (session_utils.py)
- 기존 lang2sql.py에서 UI 로직만 유지
> refactor: Lang2SQL 페이지 코드 모듈화
